runtime: nodejs20
env: standard
instance_class: F1

service: api

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

handlers:
  - url: /.*
    script: auto
    secure: always